### ISSUE TITLE
Data/code for published papers has omitted some recent significant projects

### ISSUE THREAD

**Issue by poldrack** [poldracklab/poldracklab.github.io#2]
from https://github.com/poldrack/poldracklab-staging.github.io/issues/6

**Comment by bissettp** [comment]
Here is the link for Bissett, Jones, et al. 2021 Sci Adv: http://doi.org/10.5281/zenodo.4432816).

Here is the link for Eisenberg et al., 2019: 
https://github.com/IanEisenberg/Self_Regulation_Ontology/tree/master/Data/Complete_02-16-2019

**Comment by poldrack** [comment]
this page has been refactored to automatically include listings of code/data/OSF registry for any pages that have those links the academicdb database. if there are any additional links to be added, please add them to academicdb/links.csv and I will rebuild the database using those which will automatically add them
