### ISSUE TITLE
Invite Yarik to create a codespell action

### ISSUE THREAD

**Issue by effigies** [poldracklab/poldracklab.github.io#32]
@yarikoptic Want to run your magic script?

**Comment by poldrack** [comment]
This action is currently breaking the the automated build, it seems to be thinking that a last name (Bui) is a misspelling. I'm going to turn it off for now until there is a way to fix this since I need to build.

**Comment by yarikoptic** [comment]
I would just whitelist in https://github.com/poldracklab/poldracklab.github.io/blob/main/.codespellrc#L6

Not if words in the last entry, come separated and lower case. If regex - python regex

**Comment by poldrack** [comment]
thanks!  fixed in 4f6fd2c
