### ISSUE TITLE
Funding - add graduate student funding

### ISSUE THREAD

**Issue by ricardjocelyn** [poldracklab/poldracklab.github.io#51]
**Non-exhaustive list of graduate research fellowships and additional funding opportunities:**

1) [NSF Graduate Research Fellowship Program (GRFP)](https://www.nsfgrfp.org)
2) [NDSEG Fellowship Program](https://ndseg.sysplus.com)
3) [PD Soros Fellowship Program](https://www.pdsoros.org)
4) [Knight-Hennessy Scholars Program](https://knight-hennessy.stanford.edu)
5) [Stanford RAISE: Research, Action, and Impact through Strategic Engagement Doctoral Fellowship](https://vpge.stanford.edu/fellowships-funding/RAISE)
6) [Stanford DARE: Diversifying Academia, Recruiting Excellence Fellowship](https://vpge.stanford.edu/fellowships-funding/dare)
7) [GEM Fellowship Program](https://www.gemfellowship.org)
8) [Stanford Interdisciplinary Graduate Fellowship (SIGF)](https://vpge.stanford.edu/fellowships-funding/sigf)
9) [EDGE: Enhancing Diversity in Graduate Education Doctoral Fellowship Program](https://vpge.stanford.edu/fellowships-funding/enhancing-diversity-graduate)
10) [SGF: Stanford Graduate Fellowship in Science & Engineering](https://vpge.stanford.edu/fellowships-funding/sgf)
11) [Stanford Bio-X PhD Fellowship Program](https://biox.stanford.edu/research/phd-fellows)
12) [Stanford Data Science Scholars](https://datascience.stanford.edu/programs/stanford-data-science-scholars-program/program-details).
13) [The Hertz Foundation Fellowship Program](https://www.hertzfoundation.org/the-fellowship/)
14) [Stanford Gerald J Lieberman Fellowship ](https://vpge.stanford.edu/fellowships-funding/gerald-j-lieberman-fellowship)
15) [Stanford Wu Tsai NeuroTech Program](https://neuroscience.stanford.edu/programs/training-programs-and-fellowships/neurotech-training-program)
16) [Mind, Brain, Computation and Technology (MBCT) Student Membership Program](https://neuroscience.stanford.edu/programs/training-programs-and-fellowships/mind-brain-computation-and-technology-mbct-student-membership-program)
17. [Individual Predoctoral Fellowships (F31)](https://www.niehs.nih.gov/research/supported/training/fellowships/predoctoral#:~:text=This%20initiative%20seeks%20to%20enable,participating%20NIH%20institutes%20and%20centers.)
18. [Individual Predoctoral Fellowships to Promote Diversity (F31)](https://www.niehs.nih.gov/research/supported/training/fellowships/f31)

Johns Hopkins University provides a continuously [updated source for funding opportunities for graduate students](https://research.jhu.edu/rdt/funding-opportunities/graduate/).

**Comment by ricardjocelyn** [comment]
17. [Individual Predoctoral Fellowships (F31)](https://www.niehs.nih.gov/research/supported/training/fellowships/predoctoral#:~:text=This%20initiative%20seeks%20to%20enable,participating%20NIH%20institutes%20and%20centers.)

**Comment by poldrack** [comment]
added in 4d22589
