### ISSUE TITLE
Funding - update postdoc funding links

### ISSUE THREAD

**Issue by ricardjocelyn** [poldracklab/poldracklab.github.io#56]
Update the links to the postdoc funding section:

[Sir Henry Wellcome Trust Fellowship ](https://wellcome.org/grant-funding/schemes/sir-henry-wellcome-postdoctoral-fellowships)
[BBSRC Future Leader Fellowship](https://www.ukri.org/what-we-do/developing-people-and-skills/bbsrc/fellowships/fellowships-available/) 

Add new postdoc funding:

[BWF's Career Awards at the Scientific Interface (CASI) ](https://www.bwfund.org/funding-opportunities/interfaces-in-science/career-awards-at-the-scientific-interface/)

**Comment by demidenm** [comment]
For Postdoc funding, include any caveats to funding accounts. For example, F32 NIH funding to the university come with a PTA account where the institutional allowance is included. Stanford taps the allowance for 'university insurance', so need to be cognizant that funds will deplete faster than may be presumed.

**Comment by emdupre** [comment]
We should also add Wu Tsai, since that isn't listed yet ! 😄 
https://neuroscience.stanford.edu/programs/training-programs-and-fellowships/neurosciences-postdoctoral-scholar-awards

**Comment by poldrack** [comment]
fixed in 686a336
