### ISSUE TITLE
Computing: New Delineation of Computing tab

### ISSUE THREAD

**Issue by ebridge2** [poldracklab/poldracklab.github.io#61]
Shared Computer Etiquette

Sherlock
- access + resources: accessing machine, navigating, monitoring (ndcu, shpart, shquota examples)
- job submission: example submission script? Example array job(s)?
- data management
    - how to best use storage capabilities of grouphome, oak, etc.? What data goes where?
    - how do we best use the storage capabilities of grouphome, oak, etc.? what data goes where?
    - permissioning?

TACC

**Comment by emdupre** [comment]
Affects this page : https://github.com/poldracklab/poldracklab.github.io/blob/main/labguide/computing/computing.md

**Comment by emdupre** [comment]
Task tracking here : https://github.com/emdupre/poldracklab.github.io/issues

**Comment by poldrack** [comment]
I'll leave this one to you and wait for a PR
