### ISSUE TITLE
COC: Some links lack spaces separating them from surrounding text

### ISSUE THREAD

**Issue by effigies** [poldracklab/poldracklab.github.io#67]
https://poldracklab.org/labguide/environment/code_of_conduct.html#responding-to-incidents

![image](https://github.com/poldracklab/poldracklab.github.io/assets/83442/360d0b85-2657-490a-9deb-96ef7a30dfd5)
![image](https://github.com/poldracklab/poldracklab.github.io/assets/83442/08c567a6-9f81-4c7c-9d58-9eb85fab64d5)

And maybe this should be turned into a link? (Add surrounding angle brackets, e.g., `<$URL>`.)

![image](https://github.com/poldracklab/poldracklab.github.io/assets/83442/d4b408a6-f78f-4c0f-9180-491f2db20be6)

**Comment by poldrack** [comment]
fixed in 7dea957/fa194c8
