### ISSUE TITLE
Data/code missing from task-DyVA paper

### ISSUE THREAD

**Issue by pauljaffe** [poldracklab/poldracklab.github.io#8]
We could add in the data/code from the 2023 task-DyVA paper. It looks like this would be difficult to do myself since the list is built automatically and the relevant config is encrypted (but let me know if I could somehow). 
paper DOI: [10.1038/s41562-022-01510-8](http://dx.doi.org/10.1038/s41562-022-01510-8)
code: [https://github.com/pauljaffe/task-dyva](https://github.com/pauljaffe/task-dyva)
data DOI: [10.5281/zenodo.6368412](http://dx.doi.org/10.5281/zenodo.6368412)

**Comment by poldrack** [comment]
Done!  for future reference, you can add it to academicdb/links.csv and then ask me to rebuild the database.
also - for future reference, it would be good to have a fixed reference for the code, either a github commit ID or (preferably) push the code to a zenodo repo (which is easy via the github/zenodo integration)
